### ISSUE TITLE
Error when build or check

### ISSUE THREAD

**Issue by cytown** [vincentbrison/vb-android-app-quality#13]
:app:assemble
:app:checkstyle UP-TO-DATE
:app:findbugs UP-TO-DATE
:app:compileLint
:app:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lint'.
> com.google.common.io.Files.newOutputStreamSupplier(Ljava/io/File;)Lcom/google/common/io/OutputSupplier;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.673 secs

**Comment by vincentbrison** [comment]
Thanks for your feedback !
