### ISSUE TITLE
FindBugs task: classes not found using flavors

### ISSUE THREAD

**Issue by Caerwent** [vincentbrison/vb-android-app-quality#18]
The findBugs task failed on the following line when project has flavors:
classes = files("${project.rootDir}/app/build/intermediates/classes")

The correct folder should be build using the current flavor during execution, something like that
android.applicationVariants.all { variant ->
        variant.productFlavors.each { flavor ->
            classes = classes + files("$project.buildDir/intermediates/classes/${flavor.name}/${variant.buildType.name}")
        }
}

**Comment by vincentbrison** [comment]
Hi, 

You can submit a PR if you want to fix this issue ;)

BR.
